#pragma once

#define LOAD_SOUND_MAX 50

enum SoundGroup {
	SOUND_GROUP_TITLE,
	SOUND_GROUP_PLAY,
	SOUND_GROUP_MAX
};

enum SOUND_ID {
	SOUND_ID_SE_DECISION,
	SOUND_ID_SE_PLAYER_SMALL_BULLET_SHOT,
	SOUND_ID_SE_PLAYER_LARGE_BULLET_SHOT,
	SOUND_ID_SE_ENEMY_BULLET_SHOT,
	SOUND_ID_SE_ENEMY_BULLET_HIT,
	SOUND_ID_SE_PLAYER_SMALL_BULLET_HIT,
	SOUND_ID_SE_PLAYER_LARGE_BULLET_HIT,
	SOUND_ID_BGM_TITLE_SCENE,
	SOUND_ID_BGM_PLAY_SCENE,
	SOUND_ID_MAX,
};

struct SoundParameter {
	int id;
	char file_path[128];
};

const SoundParameter SOUND_DATABASE[SOUND_ID_MAX] = {
	{SOUND_ID_SE_DECISION, "Data/Sound/SE/System/Decision.mp3"},
	{SOUND_ID_SE_PLAYER_SMALL_BULLET_SHOT, "Data/Sound/SE/Player/PlayerSmallShot.mp3"},
	{SOUND_ID_SE_PLAYER_LARGE_BULLET_SHOT, "Data/Sound/SE/Player/PlayerLargeShot.mp3"},
	{SOUND_ID_SE_ENEMY_BULLET_SHOT, "Data/Sound/SE/Enemy/EnemyShot.mp3"},
	{SOUND_ID_SE_ENEMY_BULLET_HIT, "Data/Sound/SE/Enemy/EnemyBulletHit.mp3"},
	{SOUND_ID_SE_PLAYER_SMALL_BULLET_HIT, "Data/Sound/SE/Player/PlayerSmallBulletHit.mp3"},
	{SOUND_ID_SE_PLAYER_LARGE_BULLET_HIT, "Data/Sound/SE/Player/PlayerLargeBulletHit.mp3"},
	{SOUND_ID_BGM_TITLE_SCENE, "Data/Sound/BGM/Title/Title.mp3"},
	{SOUND_ID_BGM_PLAY_SCENE, "Data/Sound/BGM/Play/Play.mp3"}
};

const int SOUND_GROUP[SOUND_GROUP_MAX][LOAD_SOUND_MAX] = {
	{ // SOUND_GROUP_TITLE
		SOUND_ID_SE_DECISION,
		SOUND_ID_BGM_TITLE_SCENE,
		-1,
	},
	{ // SOUND_GROUP_PLAY
		SOUND_ID_SE_DECISION,
		SOUND_ID_SE_PLAYER_SMALL_BULLET_SHOT,
		SOUND_ID_SE_PLAYER_LARGE_BULLET_SHOT,
		SOUND_ID_SE_ENEMY_BULLET_SHOT,
		SOUND_ID_SE_ENEMY_BULLET_HIT,
		SOUND_ID_SE_PLAYER_SMALL_BULLET_HIT,
		SOUND_ID_SE_PLAYER_LARGE_BULLET_HIT,
		SOUND_ID_BGM_PLAY_SCENE,
		-1,
	},
};
